LUC-1641: Adding `isCopy` flag
einstein/tinacms pull request #44
Opened 2023-10-24 04:35 UTC by karl00schmidt

At the moment, the duplication of an object results in an identical copy. This is the intended consequence, however, it can become hard to distinguish between a copied element, and the original, especially in id based systems. This PR should address this.

2023-10-24 16:02 UTC, beingforthebenefit reviewed
Makes sense to me. Will approve after we get your local instance up and test this thing.

2023-10-24 16:49 UTC, jcuna requested changes
Checkout my comment please

2023-10-24 16:49 UTC, jcuna commented on packages/@tinacms/fields/src/plugins/GroupListFieldPlugin.tsx
> +      isCopy: true,
Isn't this a tina's `Field` type or `GroupFieldDefinititon` type? Shouldn't we update the interface as for that as well?

2023-10-24 22:14 UTC, karl00schmidt commented
Updated to use handler instead

2023-10-25 14:43 UTC, jcuna requested changes
Looks good other than still having `isCopy`, which is not needed anymore

2023-10-25 14:43 UTC, jcuna commented on packages/@tinacms/fields/src/plugins/GroupListFieldPlugin.tsx
> +      isCopy: true,
We don't need this anymore

2023-10-25 14:57 UTC, jcuna approved these changes
Awesome stuff man. Thanks a lot!

2023-10-25 14:57 UTC, jcuna commented on packages/@tinacms/fields/src/plugins/GroupListFieldPlugin.tsx
> +  onItemDuplication?: (name: string, index: number, value: any, callback: Mutators['insert']) => void
Great use of types

2023-10-25 14:58 UTC, jcuna commented on packages/@tinacms/fields/src/plugins/GroupListFieldPlugin.tsx
> +  onItemDuplication?: (name: string, index: number, value: any, callback: Mutators['insert']) => void
Actually, can we rename that from callback to `formInsert` or something more relevant? callback is too generic

2023-10-25 15:01 UTC, jcuna approved these changes

2023-10-25 15:03 UTC, merged